// <auto-generated />
namespace addingFieldsLogin.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class calorieuser_activity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(calorieuser_activity));
        
        string IMigrationMetadata.Id
        {
            get { return "202303291343267_calorieuser_activity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
